version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Permettre l'accès à Docker depuis le container
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./cv-interactif
      dockerfile: Dockerfile
    container_name: cv_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped